### PR TITLE
Reorganize templates in subdirectories

### LINKED ISSUE #1: Reorganize templates in subdirectories
I suggest that instead of having all templates flatten in a big `templates` directory, we should make `images`/`fonts`/`colors`/ … subdirectories.

Especially since now that we'll have a dedicated repository to host templates, that would help organise them.

But also that would allow that directory structure to map the future directory structure for the template documentation which I intend to structure similarly.

### PR DESCRIPTION
**Pull request by djbe**
Fixes #1.

Needs modifications in the swiftgen CLI code.

### CODE REVIEW

**Comment by djbe** [comment]
@AliSoftware this is the subdir PR that I mentioned. The only thing it does is move the templates, and modify the testing code to handle these changes.

The only annoyance remains the iOS/macOS storyboards thing. Eventually I'd like to somehow merge these two, they are quite similar. But that'd be something for another issue/PR.

**Comment by AliSoftware** [comment]
Renaming `default` to `swift2` will be handled in a separate PR, right?

**Review by AliSoftware — APPROVED** [review]
LGTM (as long as the renaming of `default` will be handled in a separate PR).

But we should definitely test running `rake cli:install['~/Desktop/SGTest']` (after checkout-ing the appropriate branches for this PR and the one in SwiftGen), then test the local install with a named template, to ensure it finds it as expected. Haven't had time to test that on a Mac yet to fully validate this PR pair.

**Comment by djbe** [comment]
The swiftgen branch already points to this one, and I just tried the install, it works correctly.

**Comment by djbe** [comment]
Regarding your default->swift2 comment, yeah, I'm splitting everything up in small(-ish) steps.

**Pull request merged**
