### PR TITLE
Beautify the colors enums with ColorLiteral Xcode feature

### PR DESCRIPTION
**Pull request by AlexZhembl**
I thought that it would be more convenient
screen shot 2017-08-17 at 13 12 51

### CODE REVIEW

**Comment by djbe** [comment]
Nicest would be to have the colors be displayed in the documentation again. That's the whole point of the html `span` code, but it hasn't worked for me for a while.

How are those literals working for you? When I try copying those comments in a project, they're just displayed as is, in code (xcode 9).

**Comment by AlexZhembl** [comment]
@djbe 
1. About <span>: I can move it inside tag, but I think that's like "official documentation" part and literals must be around that.
2. For me it is better to see what color name refers to visual color.
And yes, we can use literals just like UIColor (without comments).

**Comment by AliSoftware** [comment]
Does adding the color literal in the documentation comment above each entry works (= is rendered as a color swatch in Xcode IDE the same as when next to the constant)? Would be more consistent to keep all comments in the same style. 

Also would by any chance adding the color literal in the doc comment make it appear in the item documentation with alt-click ?

**Comment by djbe** [comment]
This is what I'm getting:
screen shot 2017-08-17 at 12 35 54

**Comment by djbe** [comment]
Also tried wrapping it in a documentation code block, didn't help. I think the issue here is that Xcode 9 won't render literals in comments.

**Comment by AlexZhembl** [comment]
@AliSoftware @djbI 
I can add it to docs like this:
screen shot 2017-08-17 at 13 43 16

But I think there are no chance to add it to alt-click menu.

**Comment by djbe** [comment]
My point still stands that this is only a temporary solution: as far as I've checked, this doesn't work in Xcode 9. Correct me if I'm wrong though, and I'd love to have the color preview back!

But if this doesn't work in future Xcode versions, I don't see the point to adding it to the current templates.

**Comment by AliSoftware** [comment]
Well if Xcode 9 doesn't render the color in the doc comments then neither the span nor the color literal will work but at least keeping the color literal in the regular comment could make it possible to see the color at a cmd-click away if alt-click can't do better

**Comment by djbe** [comment]
That's why I attached the screenshot, even the cmd-click doesn't work.

**Comment by AlexZhembl** [comment]
@djbe Yes, Xcode 9 doesn't parse literals in comments ¯\_(ツ)_/¯

**Comment by AliSoftware** [comment]
Dammit. 

Worth reporting a bug to the Xcode team to have a way to either make the HTML span work again or get the color literals in comments back in Xcode 9. In the meantime I don't see any nice solution 😢 we could even remove the span comment as it doesn't work anymore either…

**Comment by AliSoftware** [comment]
Anyway, thanks @AlexZhembl for the PR submission, would have been a nice addition to the template indeed if Xcode 9 didn't remove that 🙃

**Comment by AlexZhembl** [comment]
@AliSoftware Thanks a lot!!!

**Comment by AliSoftware** [comment]
@AlexZhembl in SwiftGen 5.1 we added a [new template which directly generate color literals](https://github.com/SwiftGen/templates/blob/master/templates/colors/literals-swift3.stencil#L23), so that [they're used directly as the values for the constants](https://github.com/SwiftGen/templates/blob/master/Tests/Expected/Colors/literals-swift3-context-multiple.swift#L18-L19). Should help 😃 (see the CHANGELOG)

**Pull request closed without merging**
