### PR TITLE
Strings: multiple tables support

### PR DESCRIPTION
**Pull request by djbe**
This adapts both the structured and flat templates to use the table information correctly. The templates will only generate a subenum if there's more than one table.

I've also adapted the flat template to use static constants instead of cases, as discussed during one of the slack conversations. Can I leave it in this PR, or should I split that change off into it's own PR?

Refs https://github.com/SwiftGen/SwiftGenKit/pull/41

### CODE REVIEW

**Review by AliSoftware — APPROVED** [review]
LGTM for the multiple tables support

Just a quick question: wondering if the fixtures names are still consistent, looking at them? .g. I see some `…-defaults-no-comments` well if it's `--param no-comments` then it's not `defaults`, is it?

**Comment by AliSoftware** [comment]
@djbe Rebased but with conflicts so I'll let you double-check before merging

**Comment by AliSoftware** [comment]
Didn't we forget the CHANGELOG entry again?

**Comment by djbe** [comment]
I did ☹️

**Pull request merged**
